
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.util
import jpype.protocol
import org.apache.uima.cas
import org.apache.uima.collection
import org.apache.uima.jcas
import org.apache.uima.resource
import org.apache.uima.util
import typing



class Tempeval2Reader(org.apache.uima.collection.CollectionReader_ImplBase):
    FILE_BASE_SEGMENTATION: typing.ClassVar[str] = ...
    FILE_DCT: typing.ClassVar[str] = ...
    numberOfDocuments: int = ...
    hmToken: java.util.HashMap = ...
    hmDct: java.util.HashMap = ...
    PARAM_INPUTDIR: typing.ClassVar[str] = ...
    PARAM_CHARSET: typing.ClassVar[str] = ...
    PARAM_USE_SPACES: typing.ClassVar[str] = ...
    def __init__(self): ...
    def addSentenceAnnotation(self, string: str, string2: str, integer: int, integer2: int, jCas: org.apache.uima.jcas.JCas) -> int: ...
    def addTokenAnnotation(self, string: str, string2: str, integer: int, integer2: int, integer3: int, jCas: org.apache.uima.jcas.JCas) -> int: ...
    def close(self) -> None: ...
    def getNext(self, cAS: org.apache.uima.cas.CAS) -> None: ...
    def getProgress(self) -> typing.MutableSequence[org.apache.uima.util.Progress]: ...
    def hasNext(self) -> bool: ...
    @typing.overload
    def initialize(self, resourceSpecifier: org.apache.uima.resource.ResourceSpecifier, map: typing.Union[java.util.Map[str, typing.Any], typing.Mapping[str, typing.Any]]) -> bool: ...
    @typing.overload
    def initialize(self) -> None: ...
    def resetParentheses(self, string: str) -> str: ...
    def setDocumentCreationTime(self, string: str, list: java.util.List[typing.Union[java.io.File, jpype.protocol.SupportsPath]], jCas: org.apache.uima.jcas.JCas) -> None: ...
    def setTextSentencesTokens(self, string: str, list: java.util.List[typing.Union[java.io.File, jpype.protocol.SupportsPath]], jCas: org.apache.uima.jcas.JCas) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("de.unihd.dbs.uima.reader.tempeval2reader")``.

    Tempeval2Reader: typing.Type[Tempeval2Reader]
